<?php
echo '<?php';
echo '/*';
echo '* Template Name: 2021_Election';
echo '* Template Post Type: post, page, product';
echo '*/';
echo '?>';
echo '<!DOCTYPE html>';
echo '<html>';
echo '<html lang="en>';
echo '<head>';
echo '<title>Guide to 2021 Tredyffrin-Easttown Local Elections</title>';
echo '<meta charset="UTF-8">';
echo '<link href="https://fonts.googleapis.com/css?family=Source+Serif+Pro|Work+Sans|Montserrat:700" rel="stylesheet">';
echo '<link rel="stylesheet" href="http://spoke.news/wp-content/themes/newsfront/2021_Election/specialstory (2).css">';
echo '<meta name="viewport" content="width=device-width,initial-scale=1.0">';
echo '</head>';
echo '<body>';
echo '<div id="container1">';
echo '';
echo '<a href="#top"><button id="myBtn" title="Go to top">Top</button></a>';
echo '';
echo '<ul id="top">';
echo '<li><a href="http://spoke.news/"><img src="http://spoke.news/wp-content/themes/newsfront/candidates/spokelogo2.png" width="180" height="32"></a></li>';
echo '</ul>';
echo '';
echo '';
echo '';
echo '<div class="fadeIn1 .visible" style="display: block;">';
echo '<h1>Guide to 2021 Tredyffrin-Easttown Local Elections</h1>';
echo '<h3>A special report contributed to by staff reporters Mareska Chettiar, Oviya Ignaci, Zachary Rejonis, Zara Samdani, and webmaster<a href="mailto:acostas@spoke.news"> Shreya Vaidhyanathan. </a> <br> Podcast edited by multimedia web editor <a href="mailto:svaidhyanathan@spoke.news">Alexis Costas</a>. Code and design by co-editor-in-chief <a href="mailto:rwang@spoke.news">Reese Wang</a></h3>';
echo '</div>';
echo '<div class="fadeIn2" style="display: block;">';
echo '<p id="blurb"><i>Note from the Editor:</i><br><span class="blurbp"> In anticipation for the 2021 local elections, The Spoke compiled a podcast package for the T/E community to get to know the candidates for the school board and supervisors at-large. The interviews ran different lengths, as candidates were not limited in their time to respond. Each candidate was interviewed and asked the same four questions, with two additional questions tailored to the backgrounds of each candidate. The recorded interviews are listed below with a short bio about each candidate. To listen to the interviews, choose a race and choose your region or township, and the page will direct you to those candidates. The Spoke does not endorse any of the candidates interviewed.</span><br><span>-Alexis Costas and Reese Wang, Multimedia Web Editor and Co-Editor-in-Chief</span></p>';
echo '<br>';
echo '';
echo '';
echo '<div id="toggle">';
echo '<button class="typeofcandidates" id="schoolboardbutton" onclick="hideshow(schoolboardbutton, schoolboard, sbmap, supervisorbutton, supervisors, supmap)"> View school board candidates</button> <button class="typeofcandidates" id="supervisorbutton" onclick="hideshow(supervisorbutton, supervisors, supmap, schoolboardbutton, schoolboard, sbmap)"> View supervisor at-large candidates</button>';
echo '</div>';
echo '';
echo '</div>';
echo '<!-- <p style="color: red;"> inside black </p>-->';
echo '';
echo '<div id="sbmap">';
echo '<div class="fadeIn2" style="display: block;"> <p> <b>Description of a school board member: </b>Work without salary to set priorities for the schools and the T/E district based on what they believe the needs of the school community to be. Responsibilities include monthly school board meetings and committee meetings. </p> </div>';
echo '';
echo '<!-- enter here-->';
echo '<div class="table">';
echo '<div class="mapcontainer">';
echo '<a class="clean" href="#section1">';
echo '<img class="map3" src="http://spoke.news/wp-content/themes/newsfront/candidates/realregion1.png"></a>';
echo '</div>';
echo '';
echo '<div class="mapcontainer">';
echo '<a class="clean" href="#section2">';
echo '<img class="map2" src="http://spoke.news/wp-content/themes/newsfront/candidates/realregion2.png">';
echo '</a>';
echo '</div>';
echo '';
echo '<div class="mapcontainer">';
echo '<a class="clean" href="#section3">';
echo '<img class="map1" src="http://spoke.news/wp-content/themes/newsfront/candidates/realregion3.png">';
echo '</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="table">';
echo '<a id="west" href="#section1"> REGION 1 </a>';
echo '<a id="middle" href="#section2"> REGION 2 </a>';
echo '<a id="east" href="#section3"> REGION 3 </a>';
echo '</div>';
echo '<div class="table" id="maptable">';
echo '<div class="mapcontainer2">';
echo '<button class="accordion" id="polleast">Current School board members (election year)</button>';
echo '<div class="panel" style="max-width: 210.012px;">';
echo '<p>';
echo 'Roberta Hotinski (2023)<br> Todd Kantorczyk (2023) <br> One seat up for election';
echo '</p>';
echo '</div>';
echo '</div>';
echo '<div class="mapcontainer2">';
echo '<button class="accordion" id="pollmiddle">Current School board members (election year)</button>';
echo '<div class="panel" style="max-width: 210.012px;">';
echo '<p>';
echo 'Michele Burger (2023) <br> Stacy Stone (2023) <br> One seat up for election';
echo '</p>';
echo '</div>';
echo '</div>';
echo '<div class="mapcontainer2">';
echo '<button class="accordion" id="pollwest">Current School board members (election year)</button>';
echo '<div class="panel" style="max-width: 210.012px;">';
echo '<p>';
echo 'Sue Tiede (2023) <br> Tina Whitlow (2023) <br> Two seats up for election';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- end of buttons here-->';
echo '</div>';
echo '<div id="supmap">';
echo '<div class="fadeIn2" style="display: block;"> <p> <b> Description of supervisor at-large: </b>Establish township policies, oversee funding for emergency services, and fund public use facilities. Appoint township officials. At-large supervisors supervise the entire township.  </p> </div>';
echo '<!-- insert here-->';
echo '';
echo '<div id="toggle">';
echo '<a href="#section4"><button class="typeofcandidates"> Tredyffrin At-large</button></a> <a href="#section5"><button class="typeofcandidates">Easttown At-large </button> </a>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<!--<p> outside of black</p> -->';
echo '</div>';
echo '';
echo '';
echo '</div>';
echo '';
echo '<!-- here are the candidates!!-->';
echo '<div id="schoolboard">';
echo '<div id="section1">';
echo '<div class="dark">';
echo '<h2>REGION ONE:</h2><!--h2 id = "pop">&nbsp;(MIDDLE)</h2-->';
echo '<br><h6>1 seat available, 2 candidates</h6>';
echo '</div>';
echo '';
echo '<div class="blue">';
echo '<div class="card">';
echo '<img class="headshot" src="http://spoke.news/wp-content/themes/newsfront/2021_Election/headshots/yolanda allen.png">';
echo '<h4>Dr. Yolanda Allen (D)</h4>';
echo '<p> <b> Career Background:</b> Director of Workforce Career Services for the State of New Jersey and community volunteer for the youth. <br> <b> Relationship with Community:</b> Resident of Tredyffrin-Easttown, volunteer with various community-based organizations. <br> <b> Passionate about:</b> Student health and success, COVID-19 reopening, and financial decisions.</p>';
echo '';
echo '<audio src="http://spoke.news/wp-content/themes/newsfront/2021_Election/podcast/Yolanda Allen.mp3" type="audio/mpeg" controls> </audio>';
echo '<p><i>For more information, visit <a target="_blank" href="https://www.preservingexcellence.com/">Allen's website</a></i></p>';
echo '</div>';
echo '</div>';
echo '<!--hr class = "style4"-->';
echo '<div class="red">';
echo '<div class="card">';
echo '<img class="headshot" src="http://spoke.news/wp-content/themes/newsfront/2021_Election/headshots/Leslie Elken.png">';
echo '<h4>Leslie Elken (R)</h4>';
echo '<p> <b> Career Background:</b> Eastern University College of Business and Leadership affiliate professor.<br> <b> Relationship with Community:</b> Resident of Tredyffrin-Easttown, parent of Conestoga senior. Previous 9th Grade Honors World Literature teacher at Conestoga High School.<br> <b> Passionate about:</b> Transparency, financial decisions, and quality of education.</p>';
echo '<audio src="http://spoke.news/wp-content/themes/newsfront/2021_Election/podcast/Leslie Elken.mp3" type="audio/mpeg" controls> </audio>';
echo '<p><i>For more information, visit <a target="_blank" href="https://elkenforschoolboard.com/">Elken's website</a></i></p>';
echo '</div>';
echo '</div>';
echo '</div><!--END SECTION 1-->';
echo '<div id="section2">';
echo '<div class="dark">';
echo '<h2>REGION TWO:</h2><!--h2 id = "pop">&nbsp;(MIDDLE)</h2-->';
echo '<br><h6>1 seat available, 2 candidates</h6>';
echo '</div>';
echo '<div class="blue">';
echo '<div class="card">';
echo '<img class="headshot" src="http://spoke.news/wp-content/themes/newsfront/2021_Election/headshots/Robert Singh.png">';
echo '<h4>Dr. Robert Singh (D)</h4>';
echo '<p> <b> Career Background:</b> Vascular surgeon and Chief Medical Officer of The Infusion Center of Philadelphia.<br> <b> Relationship with Community:</b> Resident of Chesterbrook, parent of two Conestoga graduates and one Conestoga junior. <br> <b> Passionate about:</b> Budget proposals, financial decisions, and mental health. </p>';
echo '<audio src="http://spoke.news/wp-content/themes/newsfront/2021_Election/podcast/Robert Singh.mp3" type="audio/mpeg" controls> </audio>';
echo '<p><i>For more information, visit <a target="_blank" href="https://www.robertsinghforschoolboard.com/">Singh's website</a></i></p>';
echo '</div>';
echo '</div>';
echo '<!--hr class = "style4"-->';
echo '<div class="red">';
echo '<div class="card">';
echo '<img class="headshot" src="http://spoke.news/wp-content/themes/newsfront/2021_Election/headshots/deana wang.png">';
echo '<h4>Deana Wang (R)</h4>';
echo '<p> <b> Career Background:</b> Background in business development and pharmaceutical drug development. <br> <b> Relationship with Community:</b> Resident of 12 years, parent of one Conestoga graduate and one middle schooler. Founder of Chinese American Parent Association - T/E. <br> <b> Passionate about:</b> Transparency, financial decisions, and quality of education. </p>';
echo '<audio src="http://spoke.news/wp-content/themes/newsfront/2021_Election/podcast/Deana Wang.mp3" type="audio/mpeg" controls> </audio>';
echo '<p><i>For more information, visit <a target="_blank" href="https://votedeana.com/">Wang's website</a></i></p>';
echo '</div>';
echo '</div>';
echo '</div><!-- END SECTION 2-->';
echo '<div id="section3">';
echo '<div class="dark">';
echo '<h2>REGION THREE:</h2><!--h2 id = "pop">&nbsp;(MIDDLE)</h2-->';
echo '<br><h6>2 seats available, 4 candidates</h6>';
echo '</div>';
echo '<div class="blue">';
echo '<div class="card">';
echo '<img class="headshot" src="http://spoke.news/wp-content/themes/newsfront/2021_Election/headshots/Susan Audrain copy.png">';
echo '<h4>Susan Audrain (D)</h4>';
echo '<p> <b> Career Background:</b> Retired, background in nursing and hospital administration.<br> <b> Relationship with Community:</b> Resident of 5 years, with two grandsons in Berwyn. <br> <b> Passionate about:</b> Student well-being, informing taxpayers, and communication with constituents. </p>';
echo '<audio src="http://spoke.news/wp-content/themes/newsfront/2021_Election/podcast/Susan Audrain.mp3" type="audio/mpeg" controls> </audio>';
echo '<p><i>For more information, visit <a target="_blank" href="https://ttdems.com/meet-the-2021-candidates/">'Tredyffrin Township Democrats</a></i></p>';
echo '</div>';
echo '</div>';
echo '<!--hr class = "style4"-->';
echo '<div class="red">';
echo '<div class="card">';
echo '<img class="headshot" src="http://spoke.news/wp-content/themes/newsfront/2021_Election/headshots/Rachel Kill.png">';
echo '<h4>Rachel Kill (R)</h4>';
echo '<p> <b> Career Background:</b> Background in financial and credit underwriting. Current home office underwriter. <br> <b> Relationship with Community:</b> Resident of Devon. <br> <b> Passionate about:</b> Budget proposals, financial decisions, and mental health. </p>';
echo '<audio src="http://spoke.news/wp-content/themes/newsfront/2021_Election/podcast/Rachel Kill.mp3" type="audio/mpeg" controls> </audio>';
echo '<p><i>For more information, visit <a target="_blank" href="https://voteforchangete.com/">Kill and Nolan's website</a></i></p>';
echo '</div>';
echo '';
echo '</div>';
echo '<div class="red">';
echo '<div class="card">';
echo '<img class="headshot" src="http://spoke.news/wp-content/themes/newsfront/2021_Election/headshots/bill nolan.png">';
echo '<h4>Bill Nolan (R)</h4>';
echo '<p> <b> Career Background:</b> Retired, background in finance and accounting. Handled contracts at the Department of Defense and served in the Vietnam War.<br> <b> Relationship with Community:</b> Resident of 30 years, husband of retired Beaumont teacher. <br> <b> Passionate about:</b> Student success, fiscal policy, and student safety. </p>';
echo '<audio src="http://spoke.news/wp-content/themes/newsfront/2021_Election/podcast/Bill Nolan.mp3" type="audio/mpeg" controls> </audio>';
echo '<p><i>For more information, visit <a target="_blank" href="https://voteforchangete.com/">Kill and Nolan's website</a></i></p>';
echo '</div>';
echo '</div>';
echo '<!--hr class = "style4"-->';
echo '<div class="blue">';
echo '<div class="card">';
echo '<img class="headshot" src="http://spoke.news/wp-content/themes/newsfront/2021_Election/headshots/maryann piccioni.png">';
echo '<h4>MaryAnn Piccioni (D)</h4>';
echo '<p> <b> Career Background:</b> Development Director for the Easttown Library, community volunteer for the youth. <br> <b> Relationship with Community:</b> Resident of 36 years, parent of four Conestoga graduates. <br> <b> Passionate about:</b> Diversity and inclusion, providing students at-home and in-school resources, and practicing tolerance. </p>';
echo '<audio src="http://spoke.news/wp-content/themes/newsfront/2021_Election/podcast/MaryAnn Piccioni.mp3" type="audio/mpeg" controls> </audio>';
echo '<p><i>For more information, visit <a target="_blank" href="https://ttdems.com/meet-the-2021-candidates/">Tredyffrin Township Democrats</a></i></p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div id="supervisors">';
echo '<div id="section4">';
echo '<div class="dark">';
echo '<h2>TREDYFFRIN TOWNSHIP:</h2><!--h2 id = "pop">&nbsp;(MIDDLE)</h2-->';
echo '<br><h6>1 seat available, 2 candidates</h6>';
echo '</div>';
echo '';
echo '<div class="blue">';
echo '<div class="card">';
echo '<img class="headshot" src="http://spoke.news/wp-content/themes/newsfront/2021_Election/headshots/Matt Holt.png">';
echo '<h4>Matt Holt (D)</h4>';
echo '<p><b> Incumbent</b>: elected to Board of Supervisors in 2017.<br> <b> Career Background:</b> In-house council at Bryn Mawr Trust, private practicing attorney.<br> <b> Relationship with Community:</b> Paoli resident<br> <b> Passionate about:</b> Stormwater issues, sewer maintenance, emergency services and first responders.</p>';
echo '<audio src="http://spoke.news/wp-content/themes/newsfront/2021_Election/podcast/Matt Holt (tredyffrin).mp3" type="audio/mpeg" controls> </audio>';
echo '<p><i>For more information, visit <a target="_blank" href="https://ttdems.com/person/matt-holt/">Tredyffrin Democrats</a></i></p>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<!--hr class = "style4"-->';
echo '<div class="red">';
echo '<div class="card">';
echo '<img class="headshot" src="http://spoke.news/wp-content/themes/newsfront/2021_Election/headshots/sean sweeney.png">';
echo '<h4>Sean Sweeney (R)</h4>';
echo '<p> <b> Career Background:</b> Director of 1251 Capital. Background in risk management. <br> <b> Relationship with Community:</b> Parent of three Conestoga graduates, husband of T/E school district nurse. <br> <b> Passionate about:</b> Non-partisanship, historic preservation, and taxpayer accountability.</p>';
echo '';
echo '<audio src="http://spoke.news/wp-content/themes/newsfront/2021_Election/podcast/Sean Sweeney (tredyffrin).mp3" type="audio/mpeg" controls> </audio>';
echo '<p><i>For more information, visit <a target="_blank" href="https://sweeneyforsupervisor.com/">Sweeney's website</a></i></p>';
echo '</div>';
echo '</div>';
echo '<div class="blue">';
echo '<div class="card">';
echo '<img class="headshot" src="http://spoke.news/wp-content/themes/newsfront/2021_Election/headshots/Murph Wysocki.png">';
echo '<h4>Murph Wysocki (D)</h4>';
echo '<p><b> Incumbent</b>: Elected to Board of Supervisors in 2013, current chair of Tredyffrin Board of Supervisors. <br> <b> Career Background:</b> Real estate attorney. <br> <b> Relationship with Community:</b> Resident of 43 years. <br> <b> Passionate about:</b> renewable energy in township buildings, stormwater management, and township economic development. </p>';
echo '<audio src="http://spoke.news/wp-content/themes/newsfront/2021_Election/podcast/Murph Wysocki (tredyffrin).mp3" type="audio/mpeg" controls> </audio>';
echo '<p><i>For more information, visit <a target="_blank" href="http://www.murphwysockiforsupervisor.com/">Wysocki's website</a></i></p>';
echo '</div>';
echo '</div>';
echo '<div class="red">';
echo '<div class="card">';
echo '<img class="headshot" src="http://spoke.news/wp-content/themes/newsfront/2021_Election/headshots/JIm Z.png">';
echo '<h4>Jim Zdancewicz (R)</h4>';
echo '<p><b> Career Background:</b> In-house council at Bryn Mawr Trust, private practicing attorney.<br> <b> Relationship with Community:</b> Resident of 21 years, with two kids at Conestoga High School. Currently serves on Tredyffrin Township's Foundation for Parks and Recreation. <br> <b> Passionate about:</b> fiscal discipline, logical decision-making, and transparency.</p>';
echo '<audio src="http://spoke.news/wp-content/themes/newsfront/2021_Election/podcast/Jim Zdancewicz (tredyffrin).mp3" type="audio/mpeg" controls> </audio>';
echo '<p><i>For more information, visit <a target="_blank" href="https://jimzforsupervisor.com/">Zdancewicz's website</a></i></p>';
echo '</div>';
echo '</div>';
echo '</div><!--END SECTION 1-->';
echo '<div id="section5"> <!-- glitches if re-IDed-->';
echo '<div class="dark">';
echo '<h2>EASTTOWN TOWNSHIP:</h2><!--h2 id = "pop">&nbsp;(MIDDLE)</h2-->';
echo '<br><h6>1 seat available, 2 candidates</h6>';
echo '</div>';
echo '<br> <p style="text-align: center; font-family: 'Source Serif Pro', serif"> Candidate Alex Bosco (D), did not respond to our interview request. </p>';
echo '<div class="red">';
echo '<div class="card">';
echo '<img class="headshot" src="http://spoke.news/wp-content/themes/newsfront/2021_Election/headshots/jay jennings.png">';
echo '<h4>Jay Jennings (R)</h4>';
echo '<p><b> Career Background:</b> Math teacher at Episcopal Academy. <br> <b> Relationship with Community:</b> Resident of 21 years, with two kids at Conestoga High School. Currently serves on Tredyffrin Township's Foundation for Parks and Recreation. <br> <b> Passionate about:</b> Volunteer work, working with students & parents, and transportation laws.</p>';
echo '<audio src="http://spoke.news/wp-content/themes/newsfront/2021_Election/podcast/Jay Jennings (easttown).mp3" type="audio/mpeg" controls> </audio>';
echo '<p><i>For more information, visit <a target="_blank" href="https://www.easttownrepublicans.com/jay-bio.html">Easttown Republicans</a></i></p>';
echo '</div>';
echo '</div>';
echo '<!--hr class = "style4"-->';
echo '<div class="red">';
echo '<div class="card">';
echo '<!--<img class="headshot" src="http://spoke.news/wp-content/themes/newsfront/2021_Election/headshots/.png"> -->';
echo '<h4>Alessandra Nicolas (R)</h4>';
echo '<p><b> Career Background:</b> Background in accounting and finance. <br> <b> Relationship with Community:</b> Resident of 17 years. Member of the Easttown Citizen’s Advisory Committee, among other committees.<br> <b> Passionate about:</b> Easttown values, zoning, and financial decisions. </p>';
echo '<audio src="http://spoke.news/wp-content/themes/newsfront/2021_Election/podcast/Alessandra Nicolas (easttown).mp3" type="audio/mpeg" controls> </audio>';
echo '<p><i>For more information, visit <a target="_blank" href="hhttps://www.easttownrepublicans.com/alessandra-nichols.html">Easttown Republicans</a></i></p>';
echo '</div>';
echo '</div>';
echo '<div class="blue">';
echo '<div class="card">';
echo '<img class="headshot" src="http://spoke.news/wp-content/themes/newsfront/2021_Election/headshots/erik unger.png">';
echo '<h4>Erik Unger (D)</h4>';
echo '<p><b> Career Background:</b> Civil litigation lawyer. <br> <b> Relationship with Community:</b> Resident of Easttown Township. Volunteers at the Upper Main Line YMCA. <br> <b> Passionate about:</b> Transparency, sustainability, and Easttown values. </p>';
echo '<audio src="http://spoke.news/wp-content/themes/newsfront/2021_Election/podcast/Erik Unger (easttown).mp3" type="audio/mpeg" controls> </audio>';
echo '<p><i>For more information, visit <a target="_blank" href="https://unger4supervisor.com/">Unger's website</a></i></p>';
echo '</div>';
echo '</div>';
echo '</div><!-- END SECTION 2-->';
echo '</div>';
echo '';
echo '<footer>';
echo '<hr class="style3">';
echo '<br>';
echo 'Copyright © 2021 Spoke.News. All Rights Reserved.<br>';
echo 'To Pitch A Story Idea Or Report Breaking News, Contact Us On Twitter @Thespoke Or By Email.';
echo '</footer>';
echo '<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>';
echo '<!--script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script-->';
echo '<script src="http://spoke.news/wp-content/themes/newsfront/candidates/scripts.js"></script>';
echo '';
echo '<script>';
echo 'function hideshow(element1,div1, map1, element2, div2, map2){';
echo '<!-- element1 is clicked-->';
echo 'element1.style.backgroundColor="#942847";';
echo 'element2.style.backgroundColor="gray";';
echo 'div1.style.display="block";';
echo 'div2.style.display="none";';
echo 'element1.style.color="white";';
echo 'element2.style.color="white";';
echo 'map1.style.display="block";';
echo 'map2.style.display="none";';
echo '}';
echo '</script>';
echo '';
echo '</body>';
echo '</html>';
?>